"""
Generated by claude code to download Gleise catalog of nearby stars

Downloads the Gliese CNS3 (V/70A) catalog and loads it into SQLite as:
  - gliese_bronze: raw parsed fields from catalog.dat
  - gliese_silver: filtered/cleaned with sp_class and lum_class, sorted by plx

Usage:
    python create_gliese_tables.py <path_to_db>

Requires stellar_parser.py in the same directory.
"""

import sys
import re
import io
import sqlite3
import urllib.request
import pandas as pd
from stellar_parser import parse_stellar_column

BASE_URL = "https://cdsarc.cds.unistra.fr/ftp/cats/V/70A/"
CATALOG_FILE = "catalog.dat.gz"
README_FILE = "ReadMe"

# Fixed-width column spec derived from the V/70A ReadMe.
# (start, end) are 1-based inclusive, matching the Fortran format description.
# We extract only the fields we care about; others are skipped.
COLSPECS = [
    (1,   8),   # Name       - Gliese/GJ/NN designation
    (9,  14),   # Comp       - component (A, B, etc.)
    (16, 18),   # RA_h       - RA hours (1950)
    (19, 20),   # RA_m
    (21, 24),   # RA_s
    (25, 25),   # DE_sign
    (26, 27),   # DE_d
    (28, 29),   # DE_m
    (30, 31),   # DE_s
    (32, 37),   # pm         - proper motion (arcsec/yr)
    (38, 43),   # pmPA       - proper motion PA
    (44, 49),   # RV         - radial velocity (km/s)
    (50, 54),   # Vmag       - visual magnitude
    (56, 60),   # B_V        - B-V color
    (62, 66),   # U_B        - U-B color
    (68, 72),   # Plx        - parallax (arcsec)
    (73, 76),   # e_Plx      - parallax error
    (77, 82),   # Mv         - absolute magnitude
    (83, 88),   # SpType     - spectral type
    (89, 89),   # MultFlag   - multiplicity flag
    (90, 96),   # Lum        - luminosity (solar)
    (97,102),   # Mass       - mass (solar)
]

COLNAMES = [
    'name', 'comp',
    'ra_h', 'ra_m', 'ra_s',
    'de_sign', 'de_d', 'de_m', 'de_s',
    'pm', 'pm_pa', 'rv',
    'vmag', 'b_v', 'u_b',
    'plx', 'e_plx', 'mv',
    'sptype', 'multflag',
    'lum', 'mass',
]

# Convert 1-based inclusive to 0-based half-open for pandas
COLSPECS_0 = [(s - 1, e) for s, e in COLSPECS]

SILVER_COLS = ['name', 'comp', 'vmag', 'b_v', 'plx', 'e_plx', 'mv', 'sptype', 'multflag', 'sp_class', 'lum_class']


def fetch_url(url: str) -> bytes:
    req = urllib.request.Request(url, headers={'User-Agent': 'Mozilla/5.0'})
    with urllib.request.urlopen(req, timeout=30) as r:
        return r.read()


def load_bronze(db_path: str) -> pd.DataFrame:
    print(f"Downloading {BASE_URL}{CATALOG_FILE} ...")
    import gzip
    raw = gzip.decompress(fetch_url(BASE_URL + CATALOG_FILE))

    df = pd.read_fwf(
        io.BytesIO(raw),
        colspecs=COLSPECS_0,
        names=COLNAMES,
        dtype=str,          # read everything as string first
        na_values=['', ' '],
        encoding='latin-1',
    )

    # Coerce numeric columns
    for col in ['vmag', 'b_v', 'u_b', 'plx', 'e_plx', 'mv', 'pm', 'pm_pa', 'rv', 'lum', 'mass',
                'ra_h', 'ra_m', 'ra_s', 'de_d', 'de_m', 'de_s']:
        df[col] = pd.to_numeric(df[col], errors='coerce')

    con = sqlite3.connect(db_path)
    df.to_sql('gliese_bronze', con, if_exists='replace', index=False)
    print(f"Loaded gliese_bronze: {len(df):,} rows")
    con.close()
    return df



if __name__ == '__main__':
    if len(sys.argv) != 2:
        print(f"Usage: python {sys.argv[0]} <path_to_db>")
        sys.exit(1)

    db_path = sys.argv[1]
    df = load_bronze(db_path)
