"""
Stellar classification parser.
Parses MK (Morgan-Keenan) and related notation into component columns.

AI generated by Claude Sonnet 4.6. Heavily modified by hand after generation.
prompt:

    I need a python script that can pars any stellar classification notation in a pandas column into into multiple columns.
    Type (K, A, F, G, D for dwarf, etc.), Temperature Subtype (0, 1, 2, etc...), Class (I, II, III, IV, etc), and a column for Mount Wilson class (sd, d, sg, g, c).
    Discard any other information (eq, ..., m, nn, neb, q, etc.). Not all classification strings that must be parsed will contain all this information. 

    Some examples from the dataset I am working on:
    M6-M8.5, G5, F6V, A2, K4III, G8/K0III/IV, M0V:, F5IV/V, 'F2IV(m), F2III/IV+A7:, G1.5Vb, G4III-IV, G5III SB, G8/K1(V)+(F), K2IIb-IIIa, K2IIICNpvar, sdF8:, DAw..., DB:p, DA

"""

import re
import pandas as pd


# Spectral types in order (for range resolution)
SPECTRAL_ORDER = ['O', 'B', 'A', 'F', 'G', 'K', 'M', 'L', 'T', 'Y', 'R', 'N', 'S', 'C', 'W']

# White dwarf types
WD_TYPES = {'DA', 'DB', 'DC', 'DO', 'DZ', 'DQ', 'DX', 'DAB', 'DAH', 'DAw'}

# Mount Wilson luminosity prefixes (must check before main class)
MOUNT_WILSON = {
    'sd': 'sd',   # subdwarf
    'sg': 'sg',   # subgiant (less common prefix form)
    'd':  'd',    # dwarf
    'g':  'g',    # giant
    'c':  'c',    # supergiant (luminous)
}

# Luminosity class patterns (Roman numerals, longest match first)
LUM_PATTERN = re.compile(r'(I{1,3}V?|V?I{0,3}|IV|VI{0,2})')

# Map raw luminosity strings to standard classes
LUM_NORMALIZE = {
    'Ia': 'Ia', 'Iab': 'Iab', 'Ib': 'Ib',
    'II': 'II', 'IIa': 'IIa', 'IIab': 'IIab', 'IIb': 'IIb',
    'III': 'III', 'IIIa': 'IIIa', 'IIIab': 'IIIab', 'IIIb': 'IIIb',
    'IV': 'IV', 'IVa': 'IVa', 'IVb': 'IVb',
    'V': 'V', 'Va': 'Va', 'Vb': 'Vb',
    'VI': 'VI',
}

# Luminosity class to Mount Wilson mapping
LUM_TO_MW = {
    'Ia': 'c', 'Iab': 'c', 'Ib': 'c',
    'II': 'g',
    'III': 'g', 'IIIa': 'g', 'IIIab': 'g', 'IIIb': 'g',
    'IV': 'sg', 'IVa': 'sg', 'IVb': 'sg',
    'V': 'd', 'Va': 'd', 'Vb': 'd',
    'VI': 'sd',
}


def _pick_midpoint(val_str: str) -> float | None:
    """Convert a temperature subtype like '2', '1.5', or a range to a float midpoint."""
    if val_str is None:
        return None
    val_str = val_str.strip()
    if not val_str:
        return None
    # Range like 1-3 or 1/3
    m = re.match(r'^(\d+(?:\.\d+)?)\s*[-/]\s*(\d+(?:\.\d+)?)$', val_str)
    if m:
        return (float(m.group(1)) + float(m.group(2))) / 2
    try:
        return float(val_str)
    except ValueError:
        return None


def _parse_single(token: str) -> dict:
    """Parse a single (non-compound) classification token."""
    result = {'spectral_type': None, 'temp_subtype': None, 'lum_class': None, 'mount_wilson': None}

    token = token.strip().rstrip(':').rstrip('.')

    # White dwarf check (DA, DB, etc.) — lowercase 'w' suffix is a subtype flag, keep it
    wd_match = re.match(r'^(D[ABCOZQXH]{0,2})(w)?', token, re.IGNORECASE)
    if wd_match and re.match(r'^D[ABCOZQXH]{0,2}$', wd_match.group(1), re.IGNORECASE):
        sp = wd_match.group(1).upper()
        if wd_match.group(2):
            sp += 'w'
        result['spectral_type'] = sp
        result['mount_wilson'] = 'd'
        return result

    # Mount Wilson prefix: sd, d, g, c (must precede spectral letter)
    mw_prefix = None
    mw_match = re.match(r'^(sd|sg|c(?=[A-Z])|g(?=[A-Z])|d(?=[A-Z]))', token)
    if mw_match:
        mw_prefix = MOUNT_WILSON.get(mw_match.group(1).lower())
        token = token[mw_match.end():]

    # Spectral type letter(s)
    sp_match = re.match(r'^([OBAFGKMLTYRNSCWo])', token, re.IGNORECASE)
    if not sp_match:
        return result  # unparseable

    spectral = sp_match.group(1).upper()
    result['spectral_type'] = spectral
    rest = token[sp_match.end():]

    # Temperature subtype: digits, optional decimal, optional range via - or /
    sub_match = re.match(r'^(\d+(?:\.\d+)?(?:\s*[-/]\s*\d+(?:\.\d+)?)?)', rest)
    if sub_match:
        result['temp_subtype'] = _pick_midpoint(sub_match.group(1))
        rest = rest[sub_match.end():]

    # Luminosity class — greedy from what remains, stop at non-lum chars
    # Strip leading noise chars and optional parentheses around lum class
    rest = re.sub(r'^[+\s]*', '', rest)
    rest = re.sub(r'^\(([IVab]+)\)', r'\1', rest)  # unwrap (V), (III) etc.
    # Match luminosity class: longest match first to avoid 'I' swallowing 'III'
    lum_match = re.match(
        r'^(VII?|VI|Iab|Ia|Ib|III|II|IV|V)[ab]?',
        rest
    )
    if lum_match:
        # Normalize to pure roman numerals: collapse Ia/Ib/Iab -> I, strip trailing a/b
        raw_lum = lum_match.group(1)
        lum_str = re.sub(r'^(I+)[ab]+$', r'\1', raw_lum)
        result['lum_class'] = lum_str
        if not mw_prefix:
            mw_prefix = LUM_TO_MW.get(lum_str) or LUM_TO_MW.get(raw_lum)

    if mw_prefix:
        result['mount_wilson'] = mw_prefix

    return result


def parse_stellar(classification: str) -> dict:
    """
    Parse a stellar classification string into components.
    For compound notations (ranges, slash-pairs), picks the first valid token.
    Returns dict with keys: spectral_type, temp_subtype, lum_class, mount_wilson.
    """
    if pd.isna(classification) or not str(classification).strip():
        return {'spectral_type': None, 'temp_subtype': None, 'lum_class': None, 'mount_wilson': None}

    s = str(classification).strip().strip("'\"")

    # Remove known noise suffixes and flags
    noise = re.compile(
        r'\s*(SB\d*|var|neb|comp|CN[a-z]*p?|[mp]|nn?|eq|[+]\s*[A-Z]\d*[:]?)\s*$',
        re.IGNORECASE
    )
    s = noise.sub('', s).strip()

    # Split on space to get first component (ignore secondary companions after space+letter)
    # But keep slash/hyphen notation for range handling inside _parse_single
    first_token = re.split(r'\s+', s)[0]

    # For slash-separated compound types like G8/K0III/IV or F5IV/V,
    # split on / and parse the first meaningful token, inheriting lum from later if missing
    parts = re.split(r'/', first_token)

    parsed = _parse_single(parts[0])

    # If lum class missing, look for it in subsequent slash parts
    if parsed['lum_class'] is None and len(parts) > 1:
        for p in parts[1:]:
            candidate = _parse_single(p)
            if candidate['lum_class']:
                parsed['lum_class'] = candidate['lum_class']
                if parsed['mount_wilson'] is None:
                    parsed['mount_wilson'] = candidate['mount_wilson']
                break

    return parsed


def parse_stellar_column(series: pd.Series) -> pd.DataFrame:
    """
    Apply parse_stellar to a pandas Series of classification strings.
    Returns a DataFrame with columns: spectral_type, temp_subtype, lum_class, mount_wilson.
    """
    parsed = series.apply(parse_stellar)
    return pd.DataFrame(list(parsed), index=series.index)


# --- Demo ---
if __name__ == '__main__':
    examples = [
        "M6-M8.5", "G5", "F6V", "A2", "K4III", "G8/K0III/IV",
        "M0V:", "F5IV/V", "F2IV(m)", "F2III/IV+A7:", "G1.5Vb",
        "G4III-IV", "G5III SB", "G8/K1(V)+(F)", "K2IIb-IIIa",
        "K2IIICNpvar", "sdF8:", "DAw...", "DB:p", "DA",
    ]

    df = pd.DataFrame({'classification': examples})
    result = pd.concat([df, parse_stellar_column(df['classification'])], axis=1)
    print(result.to_string(index=False))